[tool.black]
line-length = 122

[tool.flake8]
show-source = true
filename = ["*.py"]
exclude = [".git", "__pycache__", "*.pyc"]
statistics = true
max-line-length = 122
ignore = ["W503", "E203", "F401"]

[tool.isort]
atomic = true
profile = "black"
line_length = 122
skip_gitignore = true
known_first_party = ["black", "blib2to3", "blackd", "_black_version"]

[tool.pytest.ini_options]
minversion = "6.0"
pythonpath = ["src"]
filterwarnings = ["ignore::DeprecationWarning"]

[tool.pylint]
disable = [
    "redefined-outer-name",
    "too-few-public-methods",
    "cell-var-from-loop",
    "unspecified-encoding",
    "expression-not-assigned",
    "logging-format-interpolation",
    "broad-exception-caught"
]

[tool.pdm]
distribution = false

[[tool.pdm.source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"
[project]
name = "pyAvanza_v2"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "", email = ""},
]
dependencies = [
    "avanza-api==12.0.0",
    "pandas-ta",
    "yfinance",
    "pydantic",
    "mplfinance",
    "numpy",
    "telegram-send==0.34",
    "python-telegram-bot==13.13",
    "workalendar",
    "pandas-market-calendars",
    "beautifulsoup4",
    "requests-html",
    "lxml-html-clean",
    "cloudscraper",
    "pathos",
    "scipy",
    "python-dotenv>=1.1.1",
]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

[dependency-groups]
dev = [
    "black",
    "pytest",
    "pre-commit",
    "flake8-pyproject",
    "pyupgrade",
]
