from unittest import TestCase

from apis.avanza.client.models.account.positions import AccountsPositions


class Test_AccountsPositions(TestCase):
    def test_accounts_positions(self):
        mock_accounts_positions = {
            "withOrderbook": [
                {
                    "account": {
                        "id": "5554179",
                        "type": "INVESTERINGSSPARKONTO",
                        "name": "DT",
                        "urlParameterId": "pW2w96aJi5hPJVm1o6eYZw",
                        "hasCredit": False,
                    },
                    "instrument": {
                        "id": "880733",
                        "type": "FUND",
                        "name": "Avanza Global",
                        "orderbook": {
                            "id": "878733",
                            "flagCode": None,
                            "name": "Avanza Global",
                            "type": "FUND",
                            "tradeStatus": "BUYABLE_AND_SELLABLE",
                            "quote": {
                                "highest": {
                                    "value": 200.32,
                                    "unit": "SEK",
                                    "unitType": "MONETARY",
                                    "decimalPrecision": 2,
                                },
                                "lowest": {
                                    "value": 200.32,
                                    "unit": "SEK",
                                    "unitType": "MONETARY",
                                    "decimalPrecision": 2,
                                },
                                "buy": None,
                                "sell": None,
                                "latest": {
                                    "value": 200.32,
                                    "unit": "SEK",
                                    "unitType": "MONETARY",
                                    "decimalPrecision": 2,
                                },
                                "change": {
                                    "value": 0.42001,
                                    "unit": "SEK",
                                    "unitType": "MONETARY",
                                    "decimalPrecision": 6,
                                },
                                "changePercent": {
                                    "value": 0.21,
                                    "unit": "percentage",
                                    "unitType": "PERCENTAGE",
                                    "decimalPrecision": 2,
                                },
                                "updated": "2024-06-04T00:00:00",
                            },
                            "turnover": {
                                "volume": {"value": 0, "unit": "", "unitType": "UNITLESS", "decimalPrecision": 0},
                                "value": None,
                            },
                            "lastDeal": {"date": "2024-06-04", "time": None},
                        },
                        "currency": "SEK",
                        "isin": "SE0011527613",
                        "volumeFactor": 1.0,
                    },
                    "volume": {
                        "value": 19.143,
                        "unit": "",
                        "unitType": "UNITLESS",
                        "decimalPrecision": 3,
                    },
                    "value": {
                        "value": 3834.73,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 2,
                    },
                    "averageAcquiredPrice": {
                        "value": 199.550227,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 6,
                    },
                    "averageAcquiredPriceInstrumentCurrency": {
                        "value": 199.550227,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 6,
                    },
                    "acquiredValue": {
                        "value": 3819.989995461,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 9,
                    },
                    "lastTradingDayPerformance": {
                        "absolute": {
                            "value": 8.04025143,
                            "unit": "SEK",
                            "unitType": "MONETARY",
                            "decimalPrecision": 11,
                        },
                        "relative": {
                            "value": 0.21,
                            "unit": "percentage",
                            "unitType": "PERCENTAGE",
                            "decimalPrecision": 2,
                        },
                    },
                    "collateralFactor": {
                        "value": 80.0,
                        "unit": "percentage",
                        "unitType": "PERCENTAGE",
                        "decimalPrecision": 2,
                    },
                    "superInterestApproved": True,
                    "id": "5554179-878733",
                },
                {
                    "account": {
                        "id": "6574382",
                        "type": "INVESTERINGSSPARKONTO",
                        "name": "Vacation",
                        "urlParameterId": "cyy7TCG1GSoM_h-iSW3bBA",
                        "hasCredit": False,
                    },
                    "instrument": {
                        "id": "880733",
                        "type": "FUND",
                        "name": "Avanza Global",
                        "orderbook": {
                            "id": "878733",
                            "flagCode": None,
                            "name": "Avanza Global",
                            "type": "FUND",
                            "tradeStatus": "BUYABLE_AND_SELLABLE",
                            "quote": {
                                "highest": {
                                    "value": 200.32,
                                    "unit": "SEK",
                                    "unitType": "MONETARY",
                                    "decimalPrecision": 2,
                                },
                                "lowest": {
                                    "value": 200.32,
                                    "unit": "SEK",
                                    "unitType": "MONETARY",
                                    "decimalPrecision": 2,
                                },
                                "buy": None,
                                "sell": None,
                                "latest": {
                                    "value": 200.32,
                                    "unit": "SEK",
                                    "unitType": "MONETARY",
                                    "decimalPrecision": 2,
                                },
                                "change": {
                                    "value": 0.42001,
                                    "unit": "SEK",
                                    "unitType": "MONETARY",
                                    "decimalPrecision": 6,
                                },
                                "changePercent": {
                                    "value": 0.21,
                                    "unit": "percentage",
                                    "unitType": "PERCENTAGE",
                                    "decimalPrecision": 2,
                                },
                                "updated": "2024-06-04T00:00:00",
                            },
                            "turnover": {
                                "volume": {"value": 0, "unit": "", "unitType": "UNITLESS", "decimalPrecision": 0},
                                "value": None,
                            },
                            "lastDeal": {"date": "2024-06-04", "time": None},
                        },
                        "currency": "SEK",
                        "isin": "SE0011527613",
                        "volumeFactor": 1.0,
                    },
                    "volume": {
                        "value": 61.5744,
                        "unit": "",
                        "unitType": "UNITLESS",
                        "decimalPrecision": 4,
                    },
                    "value": {
                        "value": 12334.58,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 2,
                    },
                    "averageAcquiredPrice": {
                        "value": 178.650705,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 6,
                    },
                    "averageAcquiredPriceInstrumentCurrency": {
                        "value": 178.650705,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 6,
                    },
                    "acquiredValue": {
                        "value": 11000.309969952,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 10,
                    },
                    "lastTradingDayPerformance": {
                        "absolute": {
                            "value": 25.861863744,
                            "unit": "SEK",
                            "unitType": "MONETARY",
                            "decimalPrecision": 12,
                        },
                        "relative": {
                            "value": 0.21,
                            "unit": "percentage",
                            "unitType": "PERCENTAGE",
                            "decimalPrecision": 2,
                        },
                    },
                    "collateralFactor": {
                        "value": 80.0,
                        "unit": "percentage",
                        "unitType": "PERCENTAGE",
                        "decimalPrecision": 2,
                    },
                    "superInterestApproved": True,
                    "id": "6574382-878733",
                },
                {
                    "account": {
                        "id": "9568450",
                        "type": "INVESTERINGSSPARKONTO",
                        "name": "Main",
                        "urlParameterId": "xo9hpCYQdpPHwA5l5boxvA",
                        "hasCredit": False,
                    },
                    "instrument": {
                        "id": "880733",
                        "type": "FUND",
                        "name": "Avanza Global",
                        "orderbook": {
                            "id": "878733",
                            "flagCode": None,
                            "name": "Avanza Global",
                            "type": "FUND",
                            "tradeStatus": "BUYABLE_AND_SELLABLE",
                            "quote": {
                                "highest": {
                                    "value": 200.32,
                                    "unit": "SEK",
                                    "unitType": "MONETARY",
                                    "decimalPrecision": 2,
                                },
                                "lowest": {
                                    "value": 200.32,
                                    "unit": "SEK",
                                    "unitType": "MONETARY",
                                    "decimalPrecision": 2,
                                },
                                "buy": None,
                                "sell": None,
                                "latest": {
                                    "value": 200.32,
                                    "unit": "SEK",
                                    "unitType": "MONETARY",
                                    "decimalPrecision": 2,
                                },
                                "change": {
                                    "value": 0.42001,
                                    "unit": "SEK",
                                    "unitType": "MONETARY",
                                    "decimalPrecision": 6,
                                },
                                "changePercent": {
                                    "value": 0.21,
                                    "unit": "percentage",
                                    "unitType": "PERCENTAGE",
                                    "decimalPrecision": 2,
                                },
                                "updated": "2024-06-04T00:00:00",
                            },
                            "turnover": {
                                "volume": {"value": 0, "unit": "", "unitType": "UNITLESS", "decimalPrecision": 0},
                                "value": None,
                            },
                            "lastDeal": {"date": "2024-06-04", "time": None},
                        },
                        "currency": "SEK",
                        "isin": "SE0011527613",
                        "volumeFactor": 1.0,
                    },
                    "volume": {
                        "value": 392.2184,
                        "unit": "",
                        "unitType": "UNITLESS",
                        "decimalPrecision": 4,
                    },
                    "value": {
                        "value": 78569.19,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 2,
                    },
                    "averageAcquiredPrice": {
                        "value": 182.434047,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 6,
                    },
                    "averageAcquiredPriceInstrumentCurrency": {
                        "value": 182.434047,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 6,
                    },
                    "acquiredValue": {
                        "value": 71553.9900198648,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 10,
                    },
                    "lastTradingDayPerformance": {
                        "absolute": {
                            "value": 164.735650184,
                            "unit": "SEK",
                            "unitType": "MONETARY",
                            "decimalPrecision": 12,
                        },
                        "relative": {
                            "value": 0.21,
                            "unit": "percentage",
                            "unitType": "PERCENTAGE",
                            "decimalPrecision": 2,
                        },
                    },
                    "collateralFactor": {
                        "value": 80.0,
                        "unit": "percentage",
                        "unitType": "PERCENTAGE",
                        "decimalPrecision": 2,
                    },
                    "superInterestApproved": True,
                    "id": "9568450-878733",
                },
                {
                    "account": {
                        "id": "6574382",
                        "type": "INVESTERINGSSPARKONTO",
                        "name": "Vacation",
                        "urlParameterId": "cyy7TCG1GSoM_h-iSW3bBA",
                        "hasCredit": False,
                    },
                    "instrument": {
                        "id": "41467",
                        "type": "FUND",
                        "name": "Avanza Zero",
                        "orderbook": {
                            "id": "41567",
                            "flagCode": None,
                            "name": "Avanza Zero",
                            "type": "FUND",
                            "tradeStatus": "BUYABLE_AND_SELLABLE",
                            "quote": {
                                "highest": {
                                    "value": 427.9,
                                    "unit": "SEK",
                                    "unitType": "MONETARY",
                                    "decimalPrecision": 1,
                                },
                                "lowest": {
                                    "value": 427.9,
                                    "unit": "SEK",
                                    "unitType": "MONETARY",
                                    "decimalPrecision": 1,
                                },
                                "buy": None,
                                "sell": None,
                                "latest": {
                                    "value": 427.9,
                                    "unit": "SEK",
                                    "unitType": "MONETARY",
                                    "decimalPrecision": 1,
                                },
                                "change": {
                                    "value": 3.609987,
                                    "unit": "SEK",
                                    "unitType": "MONETARY",
                                    "decimalPrecision": 6,
                                },
                                "changePercent": {
                                    "value": 0.85,
                                    "unit": "percentage",
                                    "unitType": "PERCENTAGE",
                                    "decimalPrecision": 2,
                                },
                                "updated": "2024-06-05T00:00:00",
                            },
                            "turnover": {
                                "volume": {"value": 0, "unit": "", "unitType": "UNITLESS", "decimalPrecision": 0},
                                "value": None,
                            },
                            "lastDeal": {"date": "2024-06-05", "time": None},
                        },
                        "currency": "SEK",
                        "isin": "SE0001718388",
                        "volumeFactor": 1.0,
                    },
                    "volume": {
                        "value": 41.9003,
                        "unit": "",
                        "unitType": "UNITLESS",
                        "decimalPrecision": 4,
                    },
                    "value": {
                        "value": 17929.14,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 2,
                    },
                    "averageAcquiredPrice": {
                        "value": 363.961833,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 6,
                    },
                    "averageAcquiredPriceInstrumentCurrency": {
                        "value": 363.961833,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 6,
                    },
                    "acquiredValue": {
                        "value": 15250.1099912499,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 10,
                    },
                    "lastTradingDayPerformance": {
                        "absolute": {
                            "value": 151.2595382961,
                            "unit": "SEK",
                            "unitType": "MONETARY",
                            "decimalPrecision": 12,
                        },
                        "relative": {
                            "value": 0.85,
                            "unit": "percentage",
                            "unitType": "PERCENTAGE",
                            "decimalPrecision": 2,
                        },
                    },
                    "collateralFactor": {
                        "value": 80.0,
                        "unit": "percentage",
                        "unitType": "PERCENTAGE",
                        "decimalPrecision": 2,
                    },
                    "superInterestApproved": True,
                    "id": "6574382-41567",
                },
                {
                    "account": {
                        "id": "9568450",
                        "type": "INVESTERINGSSPARKONTO",
                        "name": "Main",
                        "urlParameterId": "xo9hpCYQdpPHwA5l5boxvA",
                        "hasCredit": False,
                    },
                    "instrument": {
                        "id": "41467",
                        "type": "FUND",
                        "name": "Avanza Zero",
                        "orderbook": {
                            "id": "41567",
                            "flagCode": None,
                            "name": "Avanza Zero",
                            "type": "FUND",
                            "tradeStatus": "BUYABLE_AND_SELLABLE",
                            "quote": {
                                "highest": {
                                    "value": 427.9,
                                    "unit": "SEK",
                                    "unitType": "MONETARY",
                                    "decimalPrecision": 1,
                                },
                                "lowest": {
                                    "value": 427.9,
                                    "unit": "SEK",
                                    "unitType": "MONETARY",
                                    "decimalPrecision": 1,
                                },
                                "buy": None,
                                "sell": None,
                                "latest": {
                                    "value": 427.9,
                                    "unit": "SEK",
                                    "unitType": "MONETARY",
                                    "decimalPrecision": 1,
                                },
                                "change": {
                                    "value": 3.609987,
                                    "unit": "SEK",
                                    "unitType": "MONETARY",
                                    "decimalPrecision": 6,
                                },
                                "changePercent": {
                                    "value": 0.85,
                                    "unit": "percentage",
                                    "unitType": "PERCENTAGE",
                                    "decimalPrecision": 2,
                                },
                                "updated": "2024-06-05T00:00:00",
                            },
                            "turnover": {
                                "volume": {"value": 0, "unit": "", "unitType": "UNITLESS", "decimalPrecision": 0},
                                "value": None,
                            },
                            "lastDeal": {"date": "2024-06-05", "time": None},
                        },
                        "currency": "SEK",
                        "isin": "SE0001718388",
                        "volumeFactor": 1.0,
                    },
                    "volume": {
                        "value": 163.4788,
                        "unit": "",
                        "unitType": "UNITLESS",
                        "decimalPrecision": 4,
                    },
                    "value": {
                        "value": 69952.58,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 2,
                    },
                    "averageAcquiredPrice": {
                        "value": 370.92938,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 5,
                    },
                    "averageAcquiredPriceInstrumentCurrency": {
                        "value": 370.92938,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 5,
                    },
                    "acquiredValue": {
                        "value": 60639.089927144,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 9,
                    },
                    "lastTradingDayPerformance": {
                        "absolute": {
                            "value": 590.1563427756,
                            "unit": "SEK",
                            "unitType": "MONETARY",
                            "decimalPrecision": 12,
                        },
                        "relative": {
                            "value": 0.85,
                            "unit": "percentage",
                            "unitType": "PERCENTAGE",
                            "decimalPrecision": 2,
                        },
                    },
                    "collateralFactor": {
                        "value": 80.0,
                        "unit": "percentage",
                        "unitType": "PERCENTAGE",
                        "decimalPrecision": 2,
                    },
                    "superInterestApproved": True,
                    "id": "9568450-41567",
                },
                {
                    "account": {
                        "id": "6574382",
                        "type": "INVESTERINGSSPARKONTO",
                        "name": "Vacation",
                        "urlParameterId": "cyy7TCG1GSoM_h-iSW3bBA",
                        "hasCredit": False,
                    },
                    "instrument": {
                        "id": "363",
                        "type": "FUND",
                        "name": "Swedbank Robur Technology A",
                        "orderbook": {
                            "id": "363",
                            "flagCode": None,
                            "name": "Swedbank Robur Technology A",
                            "type": "FUND",
                            "tradeStatus": "BUYABLE_AND_SELLABLE",
                            "quote": {
                                "highest": {
                                    "value": 1168.28,
                                    "unit": "SEK",
                                    "unitType": "MONETARY",
                                    "decimalPrecision": 2,
                                },
                                "lowest": {
                                    "value": 1168.28,
                                    "unit": "SEK",
                                    "unitType": "MONETARY",
                                    "decimalPrecision": 2,
                                },
                                "buy": None,
                                "sell": None,
                                "latest": {
                                    "value": 1168.28,
                                    "unit": "SEK",
                                    "unitType": "MONETARY",
                                    "decimalPrecision": 2,
                                },
                                "change": {
                                    "value": 13.949963,
                                    "unit": "SEK",
                                    "unitType": "MONETARY",
                                    "decimalPrecision": 6,
                                },
                                "changePercent": {
                                    "value": 1.21,
                                    "unit": "percentage",
                                    "unitType": "PERCENTAGE",
                                    "decimalPrecision": 2,
                                },
                                "updated": "2024-06-05T00:00:00",
                            },
                            "turnover": {
                                "volume": {"value": 0, "unit": "", "unitType": "UNITLESS", "decimalPrecision": 0},
                                "value": None,
                            },
                            "lastDeal": {"date": "2024-06-05", "time": None},
                        },
                        "currency": "SEK",
                        "isin": "SE0000538944",
                        "volumeFactor": 1.0,
                    },
                    "volume": {
                        "value": 17.8937,
                        "unit": "",
                        "unitType": "UNITLESS",
                        "decimalPrecision": 4,
                    },
                    "value": {
                        "value": 20904.85,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 2,
                    },
                    "averageAcquiredPrice": {
                        "value": 1024.147046,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 6,
                    },
                    "averageAcquiredPriceInstrumentCurrency": {
                        "value": 1024.147046,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 6,
                    },
                    "acquiredValue": {
                        "value": 18325.7799970102,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 10,
                    },
                    "lastTradingDayPerformance": {
                        "absolute": {
                            "value": 249.6164529331,
                            "unit": "SEK",
                            "unitType": "MONETARY",
                            "decimalPrecision": 12,
                        },
                        "relative": {
                            "value": 1.21,
                            "unit": "percentage",
                            "unitType": "PERCENTAGE",
                            "decimalPrecision": 2,
                        },
                    },
                    "collateralFactor": {
                        "value": 70.0,
                        "unit": "percentage",
                        "unitType": "PERCENTAGE",
                        "decimalPrecision": 2,
                    },
                    "superInterestApproved": True,
                    "id": "6574382-363",
                },
                {
                    "account": {
                        "id": "9568450",
                        "type": "INVESTERINGSSPARKONTO",
                        "name": "Main",
                        "urlParameterId": "xo9hpCYQdpPHwA5l5boxvA",
                        "hasCredit": False,
                    },
                    "instrument": {
                        "id": "363",
                        "type": "FUND",
                        "name": "Swedbank Robur Technology A",
                        "orderbook": {
                            "id": "363",
                            "flagCode": None,
                            "name": "Swedbank Robur Technology A",
                            "type": "FUND",
                            "tradeStatus": "BUYABLE_AND_SELLABLE",
                            "quote": {
                                "highest": {
                                    "value": 1168.28,
                                    "unit": "SEK",
                                    "unitType": "MONETARY",
                                    "decimalPrecision": 2,
                                },
                                "lowest": {
                                    "value": 1168.28,
                                    "unit": "SEK",
                                    "unitType": "MONETARY",
                                    "decimalPrecision": 2,
                                },
                                "buy": None,
                                "sell": None,
                                "latest": {
                                    "value": 1168.28,
                                    "unit": "SEK",
                                    "unitType": "MONETARY",
                                    "decimalPrecision": 2,
                                },
                                "change": {
                                    "value": 13.949963,
                                    "unit": "SEK",
                                    "unitType": "MONETARY",
                                    "decimalPrecision": 6,
                                },
                                "changePercent": {
                                    "value": 1.21,
                                    "unit": "percentage",
                                    "unitType": "PERCENTAGE",
                                    "decimalPrecision": 2,
                                },
                                "updated": "2024-06-05T00:00:00",
                            },
                            "turnover": {
                                "volume": {"value": 0, "unit": "", "unitType": "UNITLESS", "decimalPrecision": 0},
                                "value": None,
                            },
                            "lastDeal": {"date": "2024-06-05", "time": None},
                        },
                        "currency": "SEK",
                        "isin": "SE0000538944",
                        "volumeFactor": 1.0,
                    },
                    "volume": {
                        "value": 82.6,
                        "unit": "",
                        "unitType": "UNITLESS",
                        "decimalPrecision": 1,
                    },
                    "value": {
                        "value": 96499.93,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 2,
                    },
                    "averageAcquiredPrice": {
                        "value": 1047.291889,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 6,
                    },
                    "averageAcquiredPriceInstrumentCurrency": {
                        "value": 1047.291889,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 6,
                    },
                    "acquiredValue": {
                        "value": 86506.3100314,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 7,
                    },
                    "lastTradingDayPerformance": {
                        "absolute": {
                            "value": 1152.2669438,
                            "unit": "SEK",
                            "unitType": "MONETARY",
                            "decimalPrecision": 9,
                        },
                        "relative": {
                            "value": 1.21,
                            "unit": "percentage",
                            "unitType": "PERCENTAGE",
                            "decimalPrecision": 2,
                        },
                    },
                    "collateralFactor": {
                        "value": 70.0,
                        "unit": "percentage",
                        "unitType": "PERCENTAGE",
                        "decimalPrecision": 2,
                    },
                    "superInterestApproved": True,
                    "id": "9568450-363",
                },
            ],
            "withoutOrderbook": [],
            "cashPositions": [
                {
                    "account": {
                        "id": "5554179",
                        "type": "INVESTERINGSSPARKONTO",
                        "name": "DT",
                        "urlParameterId": "pW2w96aJi5hPJVm1o6eYZw",
                        "hasCredit": False,
                    },
                    "totalBalance": {
                        "value": 0.88,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 4,
                    },
                    "id": "5554179-SEK",
                },
                {
                    "account": {
                        "id": "6574374",
                        "type": "AKTIEFONDKONTO",
                        "name": "6574374",
                        "urlParameterId": "EQwHHTGTKiUf1aVgpxNd0A",
                        "hasCredit": False,
                    },
                    "totalBalance": {
                        "value": 0.04,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 4,
                    },
                    "id": "6574374-SEK",
                },
                {
                    "account": {
                        "id": "6574382",
                        "type": "INVESTERINGSSPARKONTO",
                        "name": "Vacation",
                        "urlParameterId": "cyy7TCG1GSoM_h-iSW3bBA",
                        "hasCredit": False,
                    },
                    "totalBalance": {
                        "value": 0.28,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 4,
                    },
                    "id": "6574382-SEK",
                },
                {
                    "account": {
                        "id": "9568450",
                        "type": "INVESTERINGSSPARKONTO",
                        "name": "Main",
                        "urlParameterId": "xo9hpCYQdpPHwA5l5boxvA",
                        "hasCredit": False,
                    },
                    "totalBalance": {
                        "value": 0.75,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "decimalPrecision": 4,
                    },
                    "id": "9568450-SEK",
                },
            ],
            "withCreditAccount": False,
        }

        assert isinstance(AccountsPositions(**mock_accounts_positions), AccountsPositions)
