from unittest import TestCase

from services.avanza.client.models.instrument.stock import InstrumentStock


class Test_InstrumentStock(TestCase):
    def test_instrument_stock(self):
        mock_stock = {
            "orderbookId": "963856",
            "name": "Vertiseit B",
            "isin": "SE0012481133",
            "instrumentId": "966634",
            "sectors": [
                {"sectorId": "149", "sectorName": "SaaS-Leverantörer"},
                {"sectorId": "56", "sectorName": "Mjukvara"},
                {"sectorId": "38", "sectorName": "Teknologi"},
            ],
            "tradable": "BUYABLE_AND_SELLABLE",
            "listing": {
                "shortName": "VERT B",
                "tickerSymbol": "VERT B",
                "countryCode": "SE",
                "currency": "SEK",
                "marketPlaceCode": "FNSE",
                "marketPlaceName": "First North Stockholm",
                "tickSizeListId": "28",
                "marketTradesAvailable": True,
            },
            "historicalClosingPrices": {
                "oneDay": 45.3,
                "oneWeek": 45.0,
                "oneMonth": 41.6,
                "threeMonths": 31.2,
                "startOfYear": 23.5,
                "oneYear": 29.0,
                "threeYears": 28.0,
                "fiveYears": 15.3,
                "start": 16.9,
                "startDate": "2019-05-28",
            },
            "keyIndicators": {
                "numberOfOwners": 1542,
                "reportDate": "2024-04-17",
                "directYield": 0.0,
                "ordinaryDirectYield": 0.0,
                "totalDirectYield": 0.0,
                "volatility": 0.5179,
                "beta": 0.5,
                "priceEarningsRatio": 45.71,
                "priceSalesRatio": 2.58,
                "evEbitRatio": 27.04,
                "interestCoverageRatio": 3.6624,
                "returnOnEquity": 0.0708,
                "returnOnTotalAssets": 0.0517,
                "equityRatio": 0.51,
                "capitalTurnover": 0.6399,
                "operatingProfitMargin": 0.1102,
                "grossMargin": 0.6989,
                "netMargin": 0.0808,
                "marketCapital": {"value": 1074615573.0, "currency": "SEK"},
                "equityPerShare": {"value": 12.53, "currency": "SEK"},
                "turnoverPerShare": {"value": 15.73, "currency": "SEK"},
                "earningsPerShare": {"value": 1.22, "currency": "SEK"},
                "dividend": {
                    "exDate": "2024-05-03",
                    "amount": 0.0,
                    "currencyCode": "SEK",
                    "exDateStatus": "HISTORICAL",
                },
                "dividendsPerYear": 1,
                "nextReport": {"date": "2024-07-18", "reportType": "INTERIM"},
                "previousReport": {"date": "2024-04-17", "reportType": "INTERIM"},
            },
            "quote": {
                "buy": 46.3,
                "sell": 46.8,
                "last": 46.9,
                "highest": 48.4,
                "lowest": 45.0,
                "change": 1.6,
                "changePercent": 3.53,
                "spread": 1.07,
                "timeOfLast": 1717416915000,
                "totalValueTraded": 513173.3,
                "totalVolumeTraded": 11007,
                "updated": 1717418742377,
                "volumeWeightedAveragePrice": 46.62,
            },
            "type": "STOCK",
            "stock": {
                "preferred": False,
                "depositoryReceipt": False,
                "numberOfShares": 20483402,
            },
            "company": {
                "companyId": "25427",
                "description": "Vertiseit är ett SaaS-bolag inom Digital ...",
                "ceo": "Johan Lind",
                "chairman": "Ann Öberg",
                "totalNumberOfShares": 22912912,
                "homepage": "https://corporate.vertiseit.se/",
            },
            "companyEvents": {
                "events": [
                    {"date": "2024-04-17", "type": "INTERIM_REPORT"},
                    {"date": "2024-10-30", "type": "INTERIM_REPORT"},
                    {"date": "2024-02-15", "type": "ANNUAL_REPORT"},
                    {"date": "2024-07-18", "type": "INTERIM_REPORT"},
                    {"date": "2023-11-09", "type": "INTERIM_REPORT"},
                    {"date": "2024-05-02", "type": "GENERAL_MEETING"},
                    {"date": "2023-07-19", "type": "INTERIM_REPORT"},
                    {"date": "2025-02-12", "type": "ANNUAL_REPORT"},
                ],
            },
            "companyOwners": {
                "owners": [
                    {
                        "name": "KL Capital AB",
                        "percentOfCapital": 5.2,
                        "percentOfVotes": 2.3,
                    },
                    {
                        "name": "Jonas Lagerqvist (privat och via bolag)",
                        "percentOfCapital": 5.4,
                        "percentOfVotes": 8.3,
                    },
                    {
                        "name": "Alcur Fonder",
                        "percentOfCapital": 5.2,
                        "percentOfVotes": 2.5,
                    },
                    {
                        "name": "Schottenius & Partners AB",
                        "percentOfCapital": 5.9,
                        "percentOfVotes": 11.8,
                    },
                    {
                        "name": "Johan Lind",
                        "percentOfCapital": 10.7,
                        "percentOfVotes": 19.7,
                    },
                    {
                        "name": "Martin Gren (Grenspecialisten)",
                        "percentOfCapital": 4.7,
                        "percentOfVotes": 2.3,
                    },
                    {
                        "name": "Telion Og",
                        "percentOfCapital": 8.0,
                        "percentOfVotes": 3.9,
                    },
                    {
                        "name": "Oskar Edespong",
                        "percentOfCapital": 6.0,
                        "percentOfVotes": 10.1,
                    },
                    {
                        "name": "Nordea Fonder",
                        "percentOfCapital": 6.0,
                        "percentOfVotes": 2.9,
                    },
                    {
                        "name": "Adrian Nelje",
                        "percentOfCapital": 9.8,
                        "percentOfVotes": 19.2,
                    },
                ],
                "updated": "2024-03-31",
            },
            "brokerTradeSummaries": [
                {
                    "brokerCode": "ANON",
                    "sellVolume": 11007,
                    "buyVolume": 11007,
                    "netBuyVolume": 0,
                    "brokerName": "ANON",
                },
            ],
            "dividends": {
                "events": [],
                "pastEvents": [
                    {
                        "exDate": "2024-05-03",
                        "amount": 0.0,
                        "currencyCode": "SEK",
                        "dividendType": "ORDINARY",
                    },
                    {
                        "exDate": "2023-04-28",
                        "amount": 0.0,
                        "currencyCode": "SEK",
                        "dividendType": "ORDINARY",
                    },
                    {
                        "exDate": "2022-04-28",
                        "amount": 0.0,
                        "currencyCode": "SEK",
                        "dividendType": "ORDINARY",
                    },
                    {
                        "exDate": "2021-04-28",
                        "amount": 0.0,
                        "currencyCode": "SEK",
                        "dividendType": "ORDINARY",
                    },
                    {
                        "exDate": "2020-04-28",
                        "amount": 0.0,
                        "currencyCode": "SEK",
                        "dividendType": "ORDINARY",
                    },
                ],
            },
            "tradingTerms": {
                "collateralValue": 0.2,
                "marginRequirement": 1.9,
                "shortSellable": False,
                "superInterestApproved": False,
            },
            "fundExposures": [
                {
                    "orderbookId": "1170516",
                    "name": "Alcur Grow B",
                    "exposure": 0.038,
                    "instrumentType": "FUND",
                    "countryCode": "SE",
                    "hasPosition": False,
                },
            ],
            "trades": [
                {
                    "buyer": "",
                    "seller": "",
                    "dealTime": 1717416915000,
                    "price": 46.9,
                    "volume": 4,
                    "matchedOnMarket": True,
                    "cancelled": False,
                },
                {
                    "buyer": "",
                    "seller": "",
                    "dealTime": 1717416556000,
                    "price": 46.3,
                    "volume": 22,
                    "matchedOnMarket": True,
                    "cancelled": False,
                },
                {
                    "buyer": "",
                    "seller": "",
                    "dealTime": 1717416556000,
                    "price": 46.3,
                    "volume": 28,
                    "matchedOnMarket": True,
                    "cancelled": False,
                },
                {
                    "buyer": "",
                    "seller": "",
                    "dealTime": 1717414910000,
                    "price": 47.0,
                    "volume": 85,
                    "matchedOnMarket": True,
                    "cancelled": False,
                },
                {
                    "buyer": "",
                    "seller": "",
                    "dealTime": 1717414910000,
                    "price": 47.0,
                    "volume": 75,
                    "matchedOnMarket": True,
                    "cancelled": False,
                },
                {
                    "buyer": "",
                    "seller": "",
                    "dealTime": 1717414910000,
                    "price": 47.0,
                    "volume": 16,
                    "matchedOnMarket": True,
                    "cancelled": False,
                },
                {
                    "buyer": "",
                    "seller": "",
                    "dealTime": 1717413699000,
                    "price": 46.3,
                    "volume": 5,
                    "matchedOnMarket": True,
                    "cancelled": False,
                },
                {
                    "buyer": "",
                    "seller": "",
                    "dealTime": 1717413055000,
                    "price": 47.0,
                    "volume": 85,
                    "matchedOnMarket": True,
                    "cancelled": False,
                },
                {
                    "buyer": "",
                    "seller": "",
                    "dealTime": 1717412464000,
                    "price": 47.0,
                    "volume": 20,
                    "matchedOnMarket": True,
                    "cancelled": False,
                },
                {
                    "buyer": "",
                    "seller": "",
                    "dealTime": 1717412063000,
                    "price": 47.0,
                    "volume": 50,
                    "matchedOnMarket": True,
                    "cancelled": False,
                },
            ],
            "orderDepth": {
                "receivedTime": 1717418742379,
                "levels": [
                    {
                        "buySide": {
                            "price": 46.3,
                            "priceString": "46.30",
                            "volume": 300,
                        },
                        "sellSide": {
                            "price": 46.8,
                            "priceString": "46.80",
                            "volume": 200,
                        },
                    },
                    {
                        "buySide": {
                            "price": 46.1,
                            "priceString": "46.10",
                            "volume": 488,
                        },
                        "sellSide": {
                            "price": 46.9,
                            "priceString": "46.90",
                            "volume": 238,
                        },
                    },
                    {
                        "buySide": {
                            "price": 46.0,
                            "priceString": "46.00",
                            "volume": 350,
                        },
                        "sellSide": {
                            "price": 47.0,
                            "priceString": "47.00",
                            "volume": 1915,
                        },
                    },
                    {
                        "buySide": {
                            "price": 45.5,
                            "priceString": "45.50",
                            "volume": 69,
                        },
                        "sellSide": {
                            "price": 47.1,
                            "priceString": "47.10",
                            "volume": 304,
                        },
                    },
                    {
                        "buySide": {
                            "price": 45.1,
                            "priceString": "45.10",
                            "volume": 500,
                        },
                        "sellSide": {
                            "price": 47.4,
                            "priceString": "47.40",
                            "volume": 52,
                        },
                    },
                ],
            },
            "orderDepthLevels": [
                {
                    "buySide": {"price": 46.3, "priceString": "46.30", "volume": 300},
                    "sellSide": {"price": 46.8, "priceString": "46.80", "volume": 200},
                },
                {
                    "buySide": {"price": 46.1, "priceString": "46.10", "volume": 488},
                    "sellSide": {"price": 46.9, "priceString": "46.90", "volume": 238},
                },
                {
                    "buySide": {"price": 46.0, "priceString": "46.00", "volume": 350},
                    "sellSide": {"price": 47.0, "priceString": "47.00", "volume": 1915},
                },
                {
                    "buySide": {"price": 45.5, "priceString": "45.50", "volume": 69},
                    "sellSide": {"price": 47.1, "priceString": "47.10", "volume": 304},
                },
                {
                    "buySide": {"price": 45.1, "priceString": "45.10", "volume": 500},
                    "sellSide": {"price": 47.4, "priceString": "47.40", "volume": 52},
                },
            ],
        }

        assert isinstance(InstrumentStock(**mock_stock), InstrumentStock)
