from unittest import TestCase

from apis.avanza.client.models.order.transactions import TransactionsDetails


class Test_Transactions(TestCase):
    def test_transactions(self):
        transactions_response = {
            "firstTransactionDate": "2019-04-02",
            "transactions": [
                {
                    "account": {
                        "id": "7143979",
                        "name": "hold_statistics",
                        "type": "INVESTERINGSSPARKONTO",
                        "urlParameterId": "iOMR3kJPgmgAMJfI03QIog",
                    },
                    "amount": {"decimalPrecision": 14, "unit": "SEK", "unitType": "MONETARY", "value": -1040.6},
                    "availabilityDate": None,
                    "backofficeType": "BUY",
                    "backofficeTypeText": "Köp",
                    "cancelDate": None,
                    "cancelled": False,
                    "comission": None,
                    "currencyRate": None,
                    "date": "2024-10-29T11:48:01.836",
                    "description": "Köpt 110",
                    "foreignTaxRate": None,
                    "id": "intra-day-11:48:01.836-1949352977",
                    "instrumentName": "BULL OMX X20 AVA 40",
                    "intraday": True,
                    "isin": "GB00BQRMP835",
                    "noteId": None,
                    "onCreditAccount": False,
                    "orderbook": {
                        "currency": "SEK",
                        "flagCode": "SE",
                        "id": "1665466",
                        "isin": "GB00BQRMP835",
                        "marketplace": "Nordic MTF",
                        "name": "BULL OMX X20 AVA 40",
                        "type": "CERTIFICATE",
                        "volumeFactor": 1.0,
                    },
                    "priceInAccountCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 9.46,
                    },
                    "priceInTradedCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 9.46,
                    },
                    "priceInTransactionCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 9.46,
                    },
                    "result": None,
                    "settlementDate": None,
                    "tradeDate": None,
                    "type": "BUY",
                    "volume": {"decimalPrecision": 6, "unit": "", "unitType": "UNITLESS", "value": 110.0},
                    "volumeFactor": 1.0,
                },
                {
                    "account": {
                        "id": "9568450",
                        "name": "funds",
                        "type": "INVESTERINGSSPARKONTO",
                        "urlParameterId": "xo9hpCYQdpPHwA5l5boxvA",
                    },
                    "amount": {"decimalPrecision": 14, "unit": "SEK", "unitType": "MONETARY", "value": -1999.490878},
                    "availabilityDate": None,
                    "backofficeType": "BUY",
                    "backofficeTypeText": "Köp",
                    "cancelDate": None,
                    "cancelled": False,
                    "comission": None,
                    "currencyRate": None,
                    "date": "2024-10-29T11:36:33.992",
                    "description": "Köpt 6",
                    "foreignTaxRate": None,
                    "id": "intra-day-11:36:33.992-1948674795",
                    "instrumentName": "Spiltan Globalfond Investmentbolag",
                    "intraday": True,
                    "isin": "SE0008613939",
                    "noteId": None,
                    "onCreditAccount": False,
                    "orderbook": {
                        "currency": "SEK",
                        "flagCode": None,
                        "id": "693994",
                        "isin": "SE0008613939",
                        "marketplace": "Fondmarknaden",
                        "name": "Spiltan Globalfond Investmentbolag",
                        "type": "FUND",
                        "volumeFactor": 1.0,
                    },
                    "priceInAccountCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 297.11,
                    },
                    "priceInTradedCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 297.11,
                    },
                    "priceInTransactionCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 297.11,
                    },
                    "result": None,
                    "settlementDate": None,
                    "tradeDate": None,
                    "type": "BUY",
                    "volume": {"decimalPrecision": 6, "unit": "", "unitType": "UNITLESS", "value": 6.7298},
                    "volumeFactor": 1.0,
                },
                {
                    "account": {
                        "id": "9568450",
                        "name": "funds",
                        "type": "INVESTERINGSSPARKONTO",
                        "urlParameterId": "xo9hpCYQdpPHwA5l5boxvA",
                    },
                    "amount": {"decimalPrecision": 14, "unit": "SEK", "unitType": "MONETARY", "value": -9999.979825},
                    "availabilityDate": None,
                    "backofficeType": "BUY",
                    "backofficeTypeText": "Köp",
                    "cancelDate": None,
                    "cancelled": False,
                    "comission": None,
                    "currencyRate": None,
                    "date": "2024-10-29T11:36:11.9",
                    "description": "Köpt 33",
                    "foreignTaxRate": None,
                    "id": "intra-day-11:36:11.900-1948674343",
                    "instrumentName": "Spiltan Globalfond Investmentbolag",
                    "intraday": True,
                    "isin": "SE0008613939",
                    "noteId": None,
                    "onCreditAccount": False,
                    "orderbook": {
                        "currency": "SEK",
                        "flagCode": None,
                        "id": "693994",
                        "isin": "SE0008613939",
                        "marketplace": "Fondmarknaden",
                        "name": "Spiltan Globalfond Investmentbolag",
                        "type": "FUND",
                        "volumeFactor": 1.0,
                    },
                    "priceInAccountCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 297.11,
                    },
                    "priceInTradedCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 297.11,
                    },
                    "priceInTransactionCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 297.11,
                    },
                    "result": None,
                    "settlementDate": None,
                    "tradeDate": None,
                    "type": "BUY",
                    "volume": {"decimalPrecision": 6, "unit": "", "unitType": "UNITLESS", "value": 33.6575},
                    "volumeFactor": 1.0,
                },
                {
                    "account": {
                        "id": "7143979",
                        "name": "hold_statistics",
                        "type": "INVESTERINGSSPARKONTO",
                        "urlParameterId": "iOMR3kJPgmgAMJfI03QIog",
                    },
                    "amount": {"decimalPrecision": 14, "unit": "SEK", "unitType": "MONETARY", "value": 1239.7},
                    "availabilityDate": None,
                    "backofficeType": "SELL",
                    "backofficeTypeText": "Sälj",
                    "cancelDate": None,
                    "cancelled": False,
                    "comission": None,
                    "currencyRate": None,
                    "date": "2024-10-29T11:26:35.162",
                    "description": "Sålt 70",
                    "foreignTaxRate": None,
                    "id": "intra-day-11:26:35.162-1948596576",
                    "instrumentName": "BEAR OMX X20 AVA 55",
                    "intraday": True,
                    "isin": "GB00BSJX5888",
                    "noteId": None,
                    "onCreditAccount": False,
                    "orderbook": {
                        "currency": "SEK",
                        "flagCode": "SE",
                        "id": "1858116",
                        "isin": "GB00BSJX5888",
                        "marketplace": "Nordic MTF",
                        "name": "BEAR OMX X20 AVA 55",
                        "type": "CERTIFICATE",
                        "volumeFactor": 1.0,
                    },
                    "priceInAccountCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 17.71,
                    },
                    "priceInTradedCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 17.71,
                    },
                    "priceInTransactionCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 17.71,
                    },
                    "result": None,
                    "settlementDate": None,
                    "tradeDate": None,
                    "type": "SELL",
                    "volume": {"decimalPrecision": 6, "unit": "", "unitType": "UNITLESS", "value": -70.0},
                    "volumeFactor": 1.0,
                },
                {
                    "account": {
                        "id": "5554179",
                        "name": "trade_strategies",
                        "type": "INVESTERINGSSPARKONTO",
                        "urlParameterId": "pW2w96aJi5hPJVm1o6eYZw",
                    },
                    "amount": {"decimalPrecision": 14, "unit": "SEK", "unitType": "MONETARY", "value": -1933.92},
                    "availabilityDate": None,
                    "backofficeType": "BUY",
                    "backofficeTypeText": "Köp",
                    "cancelDate": None,
                    "cancelled": False,
                    "comission": None,
                    "currencyRate": None,
                    "date": "2024-10-29T11:18:20.793",
                    "description": "Köpt 18",
                    "foreignTaxRate": None,
                    "id": "intra-day-11:18:20.793-1948549096",
                    "instrumentName": "TURBO S OMX AVA 1880",
                    "intraday": True,
                    "isin": "GB00BQRNCX05",
                    "noteId": None,
                    "onCreditAccount": False,
                    "orderbook": {
                        "currency": "SEK",
                        "flagCode": "SE",
                        "id": "1735631",
                        "isin": "GB00BQRNCX05",
                        "marketplace": "First North Stockholm",
                        "name": "TURBO S OMX AVA 1880",
                        "type": "WARRANT",
                        "volumeFactor": 1.0,
                    },
                    "priceInAccountCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 107.44,
                    },
                    "priceInTradedCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 107.44,
                    },
                    "priceInTransactionCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 107.44,
                    },
                    "result": None,
                    "settlementDate": None,
                    "tradeDate": None,
                    "type": "BUY",
                    "volume": {"decimalPrecision": 6, "unit": "", "unitType": "UNITLESS", "value": 18.0},
                    "volumeFactor": 1.0,
                },
                {
                    "account": {
                        "id": "5554179",
                        "name": "trade_strategies",
                        "type": "INVESTERINGSSPARKONTO",
                        "urlParameterId": "pW2w96aJi5hPJVm1o6eYZw",
                    },
                    "amount": {"decimalPrecision": 14, "unit": "SEK", "unitType": "MONETARY", "value": 1862.46},
                    "availabilityDate": None,
                    "backofficeType": "SELL",
                    "backofficeTypeText": "Sälj",
                    "cancelDate": None,
                    "cancelled": False,
                    "comission": None,
                    "currencyRate": None,
                    "date": "2024-10-29T11:18:10.777",
                    "description": "Sålt 18",
                    "foreignTaxRate": None,
                    "id": "intra-day-11:18:10.777-1948549026",
                    "instrumentName": "TURBO L OMX AVA 2035",
                    "intraday": True,
                    "isin": "GB00BSJW8Y22",
                    "noteId": None,
                    "onCreditAccount": False,
                    "orderbook": {
                        "currency": "SEK",
                        "flagCode": "SE",
                        "id": "1852329",
                        "isin": "GB00BSJW8Y22",
                        "marketplace": "First North Stockholm",
                        "name": "TURBO L OMX AVA 2035",
                        "type": "WARRANT",
                        "volumeFactor": 1.0,
                    },
                    "priceInAccountCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 103.47,
                    },
                    "priceInTradedCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 103.47,
                    },
                    "priceInTransactionCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 103.47,
                    },
                    "result": None,
                    "settlementDate": None,
                    "tradeDate": None,
                    "type": "SELL",
                    "volume": {"decimalPrecision": 6, "unit": "", "unitType": "UNITLESS", "value": -18.0},
                    "volumeFactor": 1.0,
                },
                {
                    "account": {
                        "id": "7144096",
                        "name": "hold_correlation",
                        "type": "INVESTERINGSSPARKONTO",
                        "urlParameterId": "WTaBcip3hPaPlUy6AKwwiw",
                    },
                    "amount": {"decimalPrecision": 14, "unit": "SEK", "unitType": "MONETARY", "value": 1928.16},
                    "availabilityDate": None,
                    "backofficeType": "SELL",
                    "backofficeTypeText": "Sälj",
                    "cancelDate": None,
                    "cancelled": False,
                    "comission": None,
                    "currencyRate": None,
                    "date": "2024-10-29T11:00:10.673",
                    "description": "Sålt 117",
                    "foreignTaxRate": None,
                    "id": "intra-day-11:00:10.673-1948339977",
                    "instrumentName": "BEAR OMX X20 AVA 55",
                    "intraday": True,
                    "isin": "GB00BSJX5888",
                    "noteId": None,
                    "onCreditAccount": False,
                    "orderbook": {
                        "currency": "SEK",
                        "flagCode": "SE",
                        "id": "1858116",
                        "isin": "GB00BSJX5888",
                        "marketplace": "Nordic MTF",
                        "name": "BEAR OMX X20 AVA 55",
                        "type": "CERTIFICATE",
                        "volumeFactor": 1.0,
                    },
                    "priceInAccountCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 16.48,
                    },
                    "priceInTradedCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 16.48,
                    },
                    "priceInTransactionCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 16.48,
                    },
                    "result": None,
                    "settlementDate": None,
                    "tradeDate": None,
                    "type": "SELL",
                    "volume": {"decimalPrecision": 6, "unit": "", "unitType": "UNITLESS", "value": -117.0},
                    "volumeFactor": 1.0,
                },
                {
                    "account": {
                        "id": "7143979",
                        "name": "hold_statistics",
                        "type": "INVESTERINGSSPARKONTO",
                        "urlParameterId": "iOMR3kJPgmgAMJfI03QIog",
                    },
                    "amount": {"decimalPrecision": 14, "unit": "SEK", "unitType": "MONETARY", "value": -1188.6},
                    "availabilityDate": None,
                    "backofficeType": "BUY",
                    "backofficeTypeText": "Köp",
                    "cancelDate": None,
                    "cancelled": False,
                    "comission": None,
                    "currencyRate": None,
                    "date": "2024-10-29T10:04:06.577",
                    "description": "Köpt 70",
                    "foreignTaxRate": None,
                    "id": "intra-day-10:04:06.577-1947363005",
                    "instrumentName": "BEAR OMX X20 AVA 55",
                    "intraday": True,
                    "isin": "GB00BSJX5888",
                    "noteId": None,
                    "onCreditAccount": False,
                    "orderbook": {
                        "currency": "SEK",
                        "flagCode": "SE",
                        "id": "1858116",
                        "isin": "GB00BSJX5888",
                        "marketplace": "Nordic MTF",
                        "name": "BEAR OMX X20 AVA 55",
                        "type": "CERTIFICATE",
                        "volumeFactor": 1.0,
                    },
                    "priceInAccountCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 16.98,
                    },
                    "priceInTradedCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 16.98,
                    },
                    "priceInTransactionCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 16.98,
                    },
                    "result": None,
                    "settlementDate": None,
                    "tradeDate": None,
                    "type": "BUY",
                    "volume": {"decimalPrecision": 6, "unit": "", "unitType": "UNITLESS", "value": 70.0},
                    "volumeFactor": 1.0,
                },
                {
                    "account": {
                        "id": "7143979",
                        "name": "hold_statistics",
                        "type": "INVESTERINGSSPARKONTO",
                        "urlParameterId": "iOMR3kJPgmgAMJfI03QIog",
                    },
                    "amount": {"decimalPrecision": 14, "unit": "SEK", "unitType": "MONETARY", "value": 1301.0},
                    "availabilityDate": None,
                    "backofficeType": "SELL",
                    "backofficeTypeText": "Sälj",
                    "cancelDate": None,
                    "cancelled": False,
                    "comission": None,
                    "currencyRate": None,
                    "date": "2024-10-29T09:52:00.59",
                    "description": "Sålt 25",
                    "foreignTaxRate": None,
                    "id": "intra-day-09:52:00.590-1947151214",
                    "instrumentName": "BULL OMX X20 AVA 41",
                    "intraday": True,
                    "isin": "GB00BSJV7977",
                    "noteId": None,
                    "onCreditAccount": False,
                    "orderbook": {
                        "currency": "SEK",
                        "flagCode": "SE",
                        "id": "1828758",
                        "isin": "GB00BSJV7977",
                        "marketplace": "Nordic MTF",
                        "name": "BULL OMX X20 AVA 41",
                        "type": "CERTIFICATE",
                        "volumeFactor": 1.0,
                    },
                    "priceInAccountCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 52.04,
                    },
                    "priceInTradedCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 52.04,
                    },
                    "priceInTransactionCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 52.04,
                    },
                    "result": None,
                    "settlementDate": None,
                    "tradeDate": None,
                    "type": "SELL",
                    "volume": {"decimalPrecision": 6, "unit": "", "unitType": "UNITLESS", "value": -25.0},
                    "volumeFactor": 1.0,
                },
                {
                    "account": {
                        "id": "7144096",
                        "name": "hold_correlation",
                        "type": "INVESTERINGSSPARKONTO",
                        "urlParameterId": "WTaBcip3hPaPlUy6AKwwiw",
                    },
                    "amount": {"decimalPrecision": 14, "unit": "SEK", "unitType": "MONETARY", "value": -1983.15},
                    "availabilityDate": None,
                    "backofficeType": "BUY",
                    "backofficeTypeText": "Köp",
                    "cancelDate": None,
                    "cancelled": False,
                    "comission": None,
                    "currencyRate": None,
                    "date": "2024-10-29T09:50:21.099",
                    "description": "Köpt 117",
                    "foreignTaxRate": None,
                    "id": "intra-day-09:50:21.099-1947075598",
                    "instrumentName": "BEAR OMX X20 AVA 55",
                    "intraday": True,
                    "isin": "GB00BSJX5888",
                    "noteId": None,
                    "onCreditAccount": False,
                    "orderbook": {
                        "currency": "SEK",
                        "flagCode": "SE",
                        "id": "1858116",
                        "isin": "GB00BSJX5888",
                        "marketplace": "Nordic MTF",
                        "name": "BEAR OMX X20 AVA 55",
                        "type": "CERTIFICATE",
                        "volumeFactor": 1.0,
                    },
                    "priceInAccountCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 16.95,
                    },
                    "priceInTradedCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 16.95,
                    },
                    "priceInTransactionCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 16.95,
                    },
                    "result": None,
                    "settlementDate": None,
                    "tradeDate": None,
                    "type": "BUY",
                    "volume": {"decimalPrecision": 6, "unit": "", "unitType": "UNITLESS", "value": 117.0},
                    "volumeFactor": 1.0,
                },
                {
                    "account": {
                        "id": "5554179",
                        "name": "trade_strategies",
                        "type": "INVESTERINGSSPARKONTO",
                        "urlParameterId": "pW2w96aJi5hPJVm1o6eYZw",
                    },
                    "amount": {"decimalPrecision": 14, "unit": "SEK", "unitType": "MONETARY", "value": -1916.28},
                    "availabilityDate": None,
                    "backofficeType": "BUY",
                    "backofficeTypeText": "Köp",
                    "cancelDate": None,
                    "cancelled": False,
                    "comission": None,
                    "currencyRate": None,
                    "date": "2024-10-29T09:48:22.245",
                    "description": "Köpt 18",
                    "foreignTaxRate": None,
                    "id": "intra-day-09:48:22.245-1947098432",
                    "instrumentName": "TURBO L OMX AVA 2035",
                    "intraday": True,
                    "isin": "GB00BSJW8Y22",
                    "noteId": None,
                    "onCreditAccount": False,
                    "orderbook": {
                        "currency": "SEK",
                        "flagCode": "SE",
                        "id": "1852329",
                        "isin": "GB00BSJW8Y22",
                        "marketplace": "First North Stockholm",
                        "name": "TURBO L OMX AVA 2035",
                        "type": "WARRANT",
                        "volumeFactor": 1.0,
                    },
                    "priceInAccountCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 106.46,
                    },
                    "priceInTradedCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 106.46,
                    },
                    "priceInTransactionCurrency": {
                        "decimalPrecision": 6,
                        "unit": "SEK",
                        "unitType": "MONETARY",
                        "value": 106.46,
                    },
                    "result": None,
                    "settlementDate": None,
                    "tradeDate": None,
                    "type": "BUY",
                    "volume": {"decimalPrecision": 6, "unit": "", "unitType": "UNITLESS", "value": 18.0},
                    "volumeFactor": 1.0,
                },
            ],
            "transactionsAfterFiltering": 11,
            "transactionsFilter": {
                "accountIds": None,
                "dateRange": {"from": "2024-10-29", "to": "2024-10-29"},
                "includeCancelled": False,
                "isin": None,
                "transactionTypes": None,
            },
        }

        assert isinstance(TransactionsDetails(**transactions_response), TransactionsDetails)
