from unittest import TestCase

from apis.avanza.client.models.instrument.etf import InstrumentETF


class TestInstrumentETF(TestCase):
    def test_etf(self):
        mock_etf = {
            "underlying": {
                "orderbookId": "961717",
                "name": "OMX Stockholm 30 ESG Responsible Index",
                "instrumentType": "INDEX",
                "quote": {
                    "last": 3002.27,
                    "highest": 3009.59,
                    "lowest": 2959.73,
                    "change": 27.54,
                    "changePercent": 0.93,
                    "timeOfLast": 1770395400000,
                    "totalValueTraded": 15684589746.26,
                    "totalVolumeTraded": 76112256,
                    "updated": 1770395400221,
                    "isRealTime": True,
                },
                "listing": {
                    "shortName": "OMXS30ESG",
                    "tickerSymbol": "OMXS30ESG",
                    "countryCode": "SE",
                    "currency": "SEK",
                    "marketPlaceCode": "XXXX",
                    "marketPlaceName": "Inofficiella (beQuoted)",
                    "tickSizeListId": "7700011",
                    "marketTradesAvailable": True,
                },
                "previousClosingPrice": 2974.73,
            },
            "orderbookId": "5510",
            "name": "XACT OMXS30 ESG (UCITS ETF)",
            "isin": "SE0000693293",
            "tradable": "BUYABLE_AND_SELLABLE",
            "listing": {
                "shortName": "XACT OMXS30",
                "tickerSymbol": "XACT OMXS30",
                "countryCode": "SE",
                "currency": "SEK",
                "marketPlaceCode": "XSTO",
                "marketPlaceName": "Stockholmsbörsen",
                "tickSizeListId": "2304",
                "marketTradesAvailable": True,
            },
            "marketPlace": {
                "marketOpen": False,
                "timeLeftMs": 46445359,
                "openingTime": "09:00:00",
                "todayClosingTime": "17:30:00",
                "normalClosingTime": "17:30:00",
            },
            "historicalClosingPrices": {
                "oneDay": 450.3,
                "oneWeek": 439.15,
                "oneMonth": 431.15,
                "threeMonths": 397.55,
                "startOfYear": 422.1,
                "oneYear": 382.7,
                "threeYears": 297.7,
                "fiveYears": 252.7,
                "tenYears": 143.35,
                "start": 77.5,
                "startDate": "2005-03-01",
            },
            "keyIndicators": {
                "direction": "Lång",
                "leverage": 1.0,
                "numberOfOwners": 5566,
                "historicYield": 0.0,
                "historicYieldDate": "2026-01-31",
            },
            "quote": {
                "buy": 455.45,
                "sell": 455.55,
                "last": 455.8,
                "highest": 456.4,
                "lowest": 448.75,
                "change": 5.5,
                "changePercent": 1.22,
                "spread": 0.02,
                "timeOfLast": 1770395456000,
                "totalValueTraded": 88165469.65,
                "totalVolumeTraded": 194482,
                "updated": 1770395456446,
                "volumeWeightedAveragePrice": 453.05,
                "isRealTime": True,
            },
            "type": "EXCHANGE_TRADED_FUND",
            "assetCategory": "Aktier",
            "category": "Hållbarhet",
            "issuer": "XACT",
            "description": "Fonden är en börshandlad indexfond och har som mål att följa utvecklingen i OMXS30™",
            "documents": {
                "kid": "https://repository.modelity.com/SHB/reports/KID/ISIN_SE0000693293_SV_SE_last.pdf",
                "prospectus": "https://handelsbanken.fondlista.se/shb/pdf/XACT_OMXS30_ESG_(UCITS_ETF)_Prospectus.pdf",
            },
            "orderDepth": {"receivedTime": 1770395100259, "levels": []},
            "brokerTradeSummaries": [],
            "fee": {"totalMonetaryFee": 10.43, "totalPercentageFee": 0.1},
            "trades": [],
            "tradingUnit": 1,
            "collateralValue": 0.8,
            "superInterestApproved": True,
            "introDate": "2000-10-28",
            "dividends": {"events": [], "pastEvents": []},
            "fundExposures": [
                {
                    "orderbookId": "5259",
                    "name": "SKF B",
                    "exposure": 0.0134791,
                    "instrumentType": "STOCK",
                    "countryCode": "SE",
                    "hasPosition": False,
                },
                {
                    "orderbookId": "5537",
                    "name": "Addtech B",
                    "exposure": 0.0126719,
                    "instrumentType": "STOCK",
                    "countryCode": "SE",
                    "hasPosition": False,
                },
                {
                    "orderbookId": "520898",
                    "name": "Lifco B",
                    "exposure": 0.0116856,
                    "instrumentType": "STOCK",
                    "countryCode": "SE",
                    "hasPosition": False,
                },
            ],
            "riskScore": "FOUR",
            "holdingPeriod": "AT_LEAST_FIVE_YEARS",
            "countryExposures": {
                "updated": "2026-01-31",
                "exposures": [
                    {"countryCode": "SE", "countryName": "Sverige", "weight": 91.063336},
                    {"countryCode": "CH", "countryName": "Schweiz", "weight": 4.755068},
                    {"countryCode": "GB", "countryName": "Storbritannien", "weight": 4.181596},
                ],
            },
            "sectorExposures": {
                "updated": "2026-01-31",
                "exposures": [
                    {"sector": "COMMUNICATIONS", "weight": 3.14683},
                    {"sector": "CONSUMER_STABLE", "weight": 2.600513},
                    {"sector": "HEALTH_CARE", "weight": 4.181597},
                    {"sector": "INDUSTRY", "weight": 45.057823},
                    {"sector": "CONSUMER_CYCLIC", "weight": 1.42388},
                    {"sector": "TECH", "weight": 8.116418},
                    {"sector": "FINANCE", "weight": 31.280467},
                    {"sector": "COMMODITIES", "weight": 4.192473},
                ],
            },
            "portfolioDate": "2026-01-31",
            "esgView": {
                "euArticleType": "ARTICLE_TYPE_EIGHT",
                "sustainabilityDevelopmentGoals": [
                    {"value": "NO_POVERTY", "name": "Ingen fattigdom", "type": "SOCIAL", "status": "NOT_REPORTED"},
                    {"value": "ZERO_HUNGER", "name": "Ingen hunger", "type": "SOCIAL", "status": "NOT_REPORTED"},
                    {
                        "value": "GOOD_HEALTH_AND_WELLBEING",
                        "name": "Hälsa och välbefinnande",
                        "type": "SOCIAL",
                        "status": "NOT_REPORTED",
                    },
                    {
                        "value": "QUALITY_EDUCATION",
                        "name": "God utbildning för alla",
                        "type": "SOCIAL",
                        "status": "NOT_REPORTED",
                    },
                    {"value": "GENDER_EQUALITY", "name": "Jämställdhet", "type": "SOCIAL", "status": "NOT_REPORTED"},
                    {
                        "value": "CLEAN_WATER_AND_SANITATION",
                        "name": "Rent vatten och sanitet för alla",
                        "type": "ENVIRONMENT",
                        "status": "NOT_REPORTED",
                    },
                    {
                        "value": "AFFORDABLE_AND_CLEAN_ENERGY",
                        "name": "Hållbar energi för alla",
                        "type": "SOCIAL",
                        "status": "NOT_REPORTED",
                    },
                    {
                        "value": "DECENT_WORK_AND_ECONOMIC_GROWTH",
                        "name": "Anständiga arbetsvillkor och ekonomisk tillväxt",
                        "type": "ECONOMIC",
                        "status": "NOT_REPORTED",
                    },
                    {
                        "value": "INDUSTRY_INNOVATION_AND_INFRASTRUCTURE",
                        "name": "Hållbar industri, innovationer och infrastruktur",
                        "type": "ECONOMIC",
                        "status": "NOT_REPORTED",
                    },
                    {
                        "value": "REDUCED_INEQUALITY",
                        "name": "Minskad ojämlikhet",
                        "type": "ECONOMIC",
                        "status": "NOT_REPORTED",
                    },
                    {
                        "value": "SUSTAINABLE_CITIES_AND_COMMUNITIES",
                        "name": "Hållbara städer och samhällen",
                        "type": "SOCIAL",
                        "status": "NOT_REPORTED",
                    },
                    {
                        "value": "RESPONSIBLE_CONSUMPTION_AND_PRODUCTION",
                        "name": "Hållbar konsumtion och produktion",
                        "type": "ECONOMIC",
                        "status": "NOT_REPORTED",
                    },
                    {
                        "value": "CLIMATE_ACTION",
                        "name": "Bekämpa klimatförändringarna",
                        "type": "ENVIRONMENT",
                        "status": "NOT_REPORTED",
                    },
                    {
                        "value": "LIFE_BELOW_WATER",
                        "name": "Hav och marina resurser",
                        "type": "ENVIRONMENT",
                        "status": "NOT_REPORTED",
                    },
                    {
                        "value": "LIFE_ON_LAND",
                        "name": "Ekosystem och biologisk mångfald",
                        "type": "ENVIRONMENT",
                        "status": "NOT_REPORTED",
                    },
                    {
                        "value": "PEACE_AND_JUSTICE_STRONG_INSTITUTIONS",
                        "name": "Fredliga och inkluderande samhällen",
                        "type": "SOCIAL",
                        "status": "NOT_REPORTED",
                    },
                    {
                        "value": "PARTNERSHIPS_TO_ACHIEVE_TO_GOAL",
                        "name": "Genomförande och globalt partnerskap",
                        "type": "OVERALL",
                        "status": "NOT_REPORTED",
                    },
                ],
            },
        }
        assert isinstance(InstrumentETF(**mock_etf), InstrumentETF)
