from unittest import TestCase

from apis.avanza.client.models.instrument.index import InstrumentIndex


class Test_InstrumentIndex(TestCase):
    def test_instrument_index(self):
        mock_index = {
            "orderbookId": "19002",
            "name": "OMX Stockholm 30",
            "isin": "SE0000337842",
            "instrumentId": "9270",
            "sectors": [],
            "tradable": "BUYABLE_AND_SELLABLE",
            "listing": {
                "shortName": "OMXS30",
                "tickerSymbol": "OMXS30",
                "countryCode": "SE",
                "currency": "SEK",
                "marketPlaceCode": "XXXX",
                "marketPlaceName": "Inofficiella (beQuoted)",
                "tickSizeListId": "7700011",
                "marketTradesAvailable": True,
            },
            "historicalClosingPrices": {
                "oneDay": 2612.02,
                "oneWeek": 2630.3,
                "oneMonth": 2540.08,
                "threeMonths": 2461.49,
                "startOfYear": 2396.07,
                "oneYear": 2292.5,
                "threeYears": 2273.35,
                "fiveYears": 1518.23,
                "tenYears": 1395.77,
                "start": 73.66,
                "startDate": "1984-01-02",
            },
            "keyIndicators": {"numberOfOwners": 0, "dividendsPerYear": 0},
            "quote": {
                "last": 2589.39,
                "highest": 2608.22,
                "lowest": 2583.66,
                "change": -22.63,
                "changePercent": -0.87,
                "timeOfLast": 1717490720000,
                "totalValueTraded": 2549052693.4,
                "totalVolumeTraded": 28836612,
                "updated": 1717490720157,
            },
            "type": "INDEX",
            "stock": {"preferred": False, "depositoryReceipt": False},
            "company": {
                "companyId": "",
                "description": "",
                "ceo": "",
                "chairman": "",
                "homepage": "",
            },
            "companyOwners": {"owners": []},
            "brokerTradeSummaries": [
                {
                    "brokerCode": "ANON",
                    "sellVolume": 28836612,
                    "buyVolume": 28836612,
                    "netBuyVolume": 0,
                    "brokerName": "ANON",
                },
            ],
            "dividends": {"events": [], "pastEvents": []},
            "tradingTerms": {
                "collateralValue": 0,
                "marginRequirement": 0,
                "shortSellable": False,
                "superInterestApproved": False,
            },
            "fundExposures": [],
            "trades": [
                {
                    "buyer": "",
                    "seller": "",
                    "dealTime": 1717490720000,
                    "price": 2589.39,
                    "volume": 735,
                    "matchedOnMarket": True,
                    "cancelled": False,
                },
                {
                    "buyer": "",
                    "seller": "",
                    "dealTime": 1717490718000,
                    "price": 2589.36,
                    "volume": 68,
                    "matchedOnMarket": True,
                    "cancelled": False,
                },
                {
                    "buyer": "",
                    "seller": "",
                    "dealTime": 1717490717000,
                    "price": 2589.37,
                    "volume": 27819,
                    "matchedOnMarket": True,
                    "cancelled": False,
                },
                {
                    "buyer": "",
                    "seller": "",
                    "dealTime": 1717490713000,
                    "price": 2589.39,
                    "volume": 3513,
                    "matchedOnMarket": True,
                    "cancelled": False,
                },
                {
                    "buyer": "",
                    "seller": "",
                    "dealTime": 1717490712000,
                    "price": 2589.37,
                    "volume": 1000,
                    "matchedOnMarket": True,
                    "cancelled": False,
                },
                {
                    "buyer": "",
                    "seller": "",
                    "dealTime": 1717490711000,
                    "price": 2589.33,
                    "volume": 5540,
                    "matchedOnMarket": True,
                    "cancelled": False,
                },
                {
                    "buyer": "",
                    "seller": "",
                    "dealTime": 1717490710000,
                    "price": 2589.34,
                    "volume": 11290,
                    "matchedOnMarket": True,
                    "cancelled": False,
                },
                {
                    "buyer": "",
                    "seller": "",
                    "dealTime": 1717490708000,
                    "price": 2588.73,
                    "volume": 794,
                    "matchedOnMarket": True,
                    "cancelled": False,
                },
                {
                    "buyer": "",
                    "seller": "",
                    "dealTime": 1717490707000,
                    "price": 2588.59,
                    "volume": 3238,
                    "matchedOnMarket": True,
                    "cancelled": False,
                },
                {
                    "buyer": "",
                    "seller": "",
                    "dealTime": 1717490706000,
                    "price": 2588.45,
                    "volume": 652,
                    "matchedOnMarket": True,
                    "cancelled": False,
                },
            ],
            "orderDepth": {},
        }

        assert isinstance(InstrumentIndex(**mock_index), InstrumentIndex)
