from unittest import TestCase

from services.avanza.client.models.order.list import Orders


class Test_Orders(TestCase):
    def test_orders(self):
        mock_orders = {
            "orders": [
                {
                    "account": {
                        "accountId": "5554179",
                        "name": {"value": "DT"},
                        "type": {"accountType": "INVESTERINGSSPARKONTO"},
                        "urlParameterId": "pW2w96aJi5hPJVm1o6eYZw",
                    },
                    "orderId": "650930897",
                    "volume": 1,
                    "price": 30.0,
                    "amount": 30.0,
                    "orderbookId": "1478248",
                    "side": "BUY",
                    "validUntil": "2024-06-07",
                    "created": "2024-06-07T13:46:33",
                    "deletable": True,
                    "modifiable": True,
                    "message": "Din order befinner sig på marknaden.",
                    "state": "ACTIVE",
                    "stateText": "Marknaden",
                    "stateMessage": "Din order befinner sig på marknaden.",
                    "orderbook": {
                        "id": "1478248",
                        "name": "BULL OMX X20 AVA 27",
                        "countryCode": "SE",
                        "currency": "SEK",
                        "instrumentType": "Certifikat",
                        "volumeFactor": "1.00",
                        "isin": "GB00BNV4KV28",
                        "mic": "NMTF",
                    },
                    "additionalParameters": {},
                },
                {
                    "account": {
                        "accountId": "5554179",
                        "name": {"value": "DT"},
                        "type": {"accountType": "INVESTERINGSSPARKONTO"},
                        "urlParameterId": "pW2w96aJi5hPJVm1o6eYZw",
                    },
                    "orderId": "650930864",
                    "volume": 1,
                    "price": 1000000.0,
                    "amount": 1000000.0,
                    "orderbookId": "1757509",
                    "side": "SELL",
                    "validUntil": "2024-06-07",
                    "created": "2024-06-07T13:41:55",
                    "deletable": True,
                    "modifiable": False,
                    "message": "Det är inte tillåtet att blanka det här värdepappret.",
                    "state": "FAILED",
                    "stateText": "Felaktig",
                    "stateMessage": "Ett fel har uppstått med din order. ...",
                    "orderbook": {
                        "id": "1757509",
                        "name": "TURBO L OMX AVA 1904",
                        "countryCode": "SE",
                        "currency": "SEK",
                        "instrumentType": "Warrant",
                        "volumeFactor": "1.00",
                        "isin": "GB00BSJJKJ23",
                        "mic": "FNSE",
                    },
                    "additionalParameters": {},
                },
                {
                    "account": {
                        "accountId": "5554179",
                        "name": {"value": "DT"},
                        "type": {"accountType": "INVESTERINGSSPARKONTO"},
                        "urlParameterId": "pW2w96aJi5hPJVm1o6eYZw",
                    },
                    "orderId": "650930863",
                    "volume": 1000000,
                    "price": 1.0,
                    "amount": 1000000.0,
                    "orderbookId": "1757509",
                    "side": "BUY",
                    "validUntil": "2024-06-07",
                    "created": "2024-06-07T13:41:54",
                    "deletable": True,
                    "modifiable": False,
                    "message": "Priset avviker från tillåtet handelsintervall. ",
                    "state": "FAILED",
                    "stateText": "Felaktig",
                    "stateMessage": "Ett fel har uppstått med din order. ...",
                    "orderbook": {
                        "id": "1757509",
                        "name": "TURBO L OMX AVA 1904",
                        "countryCode": "SE",
                        "currency": "SEK",
                        "instrumentType": "Warrant",
                        "volumeFactor": "1.00",
                        "isin": "GB00BSJJKJ23",
                        "mic": "FNSE",
                    },
                    "additionalParameters": {},
                },
            ],
            "fundOrders": [
                {
                    "account": {
                        "accountId": "5554179",
                        "name": {"value": "DT"},
                        "type": {"accountType": "INVESTERINGSSPARKONTO"},
                        "urlParameterId": "pW2w96aJi5hPJVm1o6eYZw",
                    },
                    "orderId": "650856557",
                    "volume": 5.241613,
                    "amount": 1050.0,
                    "orderbookId": "878733",
                    "side": "SELL",
                    "validUntil": "2124-06-07",
                    "created": "2024-06-07T10:20:24",
                    "deletable": True,
                    "modifiable": False,
                    "message": "Vi har tagit emot din fondorder. ...",
                    "state": "ACTIVE",
                    "stateText": "Registrerad",
                    "stateMessage": "Vi har tagit emot din fondorder. ...",
                    "orderbook": {
                        "id": "878733",
                        "name": "Avanza Global",
                        "countryCode": "SE",
                        "currency": "SEK",
                        "instrumentType": "Fond",
                        "volumeFactor": "1.00",
                        "isin": "SE0011527613",
                        "mic": "FUND",
                    },
                    "additionalParameters": {},
                    "visibleOnAccountDate": "2024-06-12",
                    "stopTime": "2024-06-10T10:00:00",
                },
            ],
        }

        assert isinstance(Orders(**mock_orders), Orders)
