name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}

    - name: Transfer files to remote server
      env:
        REMOTE_USERNAME: ${{ secrets.REMOTE_USERNAME }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ ${REMOTE_USERNAME}@${REMOTE_HOST}:/home/ubuntu/pyAvanza/
