name: Deploy to Remote Server and Update Cronjob

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install ssh-keyscan
      run: sudo apt-get install -y openssh-client

    - name: Deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_USERNAME: ${{ secrets.REMOTE_USERNAME }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts

        # Ensure the destination directory exists on the remote server
        ssh ${REMOTE_USERNAME}@${REMOTE_HOST} \
          "mkdir -p /home/ubuntu/pyAvanza/"

        # Remove all files and directories except "data", "logs", and "config"
        ssh ${REMOTE_USERNAME}@${REMOTE_HOST} \
          "find /home/ubuntu/pyAvanza/ -mindepth 1 -maxdepth 1 -type f -exec rm -f {} +"
        ssh ${REMOTE_USERNAME}@${REMOTE_HOST} \
          "find /home/ubuntu/pyAvanza/ -mindepth 1 -maxdepth 1 -type d ! -name 'data' ! -name 'logs' ! -name 'config' -exec rm -rf {} +"

        # Use rsync to copy only files under src/ directory to remote server
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" \
          ./src/ ${REMOTE_USERNAME}@${REMOTE_HOST}:/home/ubuntu/pyAvanza/

    - name: Update Crontab
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_USERNAME: ${{ secrets.REMOTE_USERNAME }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      run: |
        # Define cronjobs as a simple array of strings
        cronjobs=(
          "task_end_of_day 10 22 * * 1-5"
          "task_end_of_week 0 9 * * 6"
          "task_trade 43 9 * * 1-5"
          "copy_stats 0 * * * *"
        )

        # Fetch existing crontab
        existing_crontab=$(ssh ${REMOTE_USERNAME}@${REMOTE_HOST} "crontab -l")

        # Prepare updated crontab
        updated_crontab=""

        # Loop through existing cron jobs to filter out pyAvanza jobs
        while IFS= read -r existing_job; do
          if echo "$existing_job" | grep -q "pyAvanza"; then
            continue  # Skip pyAvanza jobs
          fi
          updated_crontab+="$existing_job\n"
        done <<< "$existing_crontab"

        # Add new cronjobs
        updated_crontab+="# pyAvanza\n"
        for job in "${cronjobs[@]}"; do
          task_name="${job%% *}"
          cron_schedule="${job#* }"

          if [ "$task_name" = "copy_stats" ]; then
            updated_crontab+="$cron_schedule sudo cp /home/ubuntu/pyAvanza/logs/daily_trading_stats_OMX.json /var/www/klechikov_dev/webApp/\n"
          else
            updated_crontab+="$cron_schedule /usr/bin/python3 /home/ubuntu/pyAvanza/$task_name.py\n"
          fi
        done

        # Update crontab on remote server
        echo -e "$updated_crontab" | ssh ${REMOTE_USERNAME}@${REMOTE_HOST} "crontab -"

        # Give permissions to print_logs.sh
        ssh ${REMOTE_USERNAME}@${REMOTE_HOST} "chmod +x /home/ubuntu/pyAvanza/print_logs.sh"
