name: Deploy to Remote Server and Update Cronjob

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install ssh-keyscan
      run: sudo apt-get install -y openssh-client

    - name: Setup SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_USERNAME: ${{ secrets.REMOTE_USERNAME }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts

        # Ensure the destination directory exists on the remote server
        ssh ${REMOTE_USERNAME}@${REMOTE_HOST} \
          "mkdir -p /home/ubuntu/pyAvanza/"

        # Use rsync to copy only files under src/ directory to remote server
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" \
          ./src/ ${REMOTE_USERNAME}@${REMOTE_HOST}:/home/ubuntu/pyAvanza/

        # Define cronjobs as a simple array of strings
        cronjobs=(
          "task_eod 0 19 * * 1-5"
        )

        # Fetch existing crontab
        existing_crontab=$(ssh ${REMOTE_USERNAME}@${REMOTE_HOST} "crontab -l")

        # Prepare updated crontab
        updated_crontab="$existing_crontab"

        # Loop through cronjobs to update crontab
        for job in "${cronjobs[@]}"; do
          # Split job into task_name and cron_schedule
          task_name="${job%% *}"
          cron_schedule="${job#* }"

          # Check if task_name already exists in crontab
          if echo "$existing_crontab" | grep -q "/home/ubuntu/pyAvanza/$task_name"; then
            # Task exists, replace old entry
            updated_crontab=$(echo "$updated_crontab" | sed -e "/\/home\/ubuntu\/pyAvanza\/$task_name/d")
          fi

          # Add the new cron job
          updated_crontab="$updated_crontab\n$cron_schedule /usr/bin/python3 /home/ubuntu/pyAvanza/$task_name.py"
        done

        # Update crontab on remote server
        echo -e "$updated_crontab" | ssh ${REMOTE_USERNAME}@${REMOTE_HOST} "crontab -"
